// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJgaReLXVQIZblDOEoDIMRn5lsjfScHJI',
    appId: '1:94447234359:web:f30c3a3c3c1e9769fbbeb2',
    messagingSenderId: '94447234359',
    projectId: 'an-najah-app',
    authDomain: 'an-najah-app.firebaseapp.com',
    storageBucket: 'an-najah-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhPexCGAAL8GV2874LDHPPky1u1zTGcf8',
    appId: '1:94447234359:android:2645c66856e2f9a6fbbeb2',
    messagingSenderId: '94447234359',
    projectId: 'an-najah-app',
    storageBucket: 'an-najah-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxmcuq46KW9UJ5c53yAi38uO6eDTKy6Qc',
    appId: '1:94447234359:ios:be62a7b7b1e67e36fbbeb2',
    messagingSenderId: '94447234359',
    projectId: 'an-najah-app',
    storageBucket: 'an-najah-app.appspot.com',
    iosBundleId: 'com.example.anNajahProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxmcuq46KW9UJ5c53yAi38uO6eDTKy6Qc',
    appId: '1:94447234359:ios:be62a7b7b1e67e36fbbeb2',
    messagingSenderId: '94447234359',
    projectId: 'an-najah-app',
    storageBucket: 'an-najah-app.appspot.com',
    iosBundleId: 'com.example.anNajahProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJgaReLXVQIZblDOEoDIMRn5lsjfScHJI',
    appId: '1:94447234359:web:6189d425155dc62cfbbeb2',
    messagingSenderId: '94447234359',
    projectId: 'an-najah-app',
    authDomain: 'an-najah-app.firebaseapp.com',
    storageBucket: 'an-najah-app.appspot.com',
  );

}